apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-configs-dev
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  application: my-app
                  environment: dev
          - git:
              repoURL: https://github.com/highonsemicolon/pathfinder.git
              revision: main
              directories:
                - path: gitops/applications/my-app/{{metadata.labels.environment}}/configs/*
  template:
    metadata:
      name: 'my-app-configs-{{path[4]}}-{{metadata.labels.environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/highonsemicolon/pathfinder.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path[4]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true