apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-istio-base-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            application: my-app
            environment: dev
  template:
    metadata:
      name: 'my-app-istio-base-{{metadata.labels.environment}}'
    spec:
      project: default
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        chart: base
        targetRevision: 1.30.0
      ignoreDifferences:
        - group: "admissionregistration.k8s.io"
          kind: "ValidatingWebhookConfiguration"
          jqPathExpressions:
            - '.webhooks[].clientConfig.caBundle'
            - '.webhooks[].failurePolicy'
      destination:
        server: '{{server}}'
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
