apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pathfinder.fullname" . }}
data:
  {{- with .Values.env.configMap }}
    {{- range $key, $val := . }}
      {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}