{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "pathfinder.fullname" . }}
  labels:
    {{- include "pathfinder.labels" . | nindent 4 }}
spec:
  selector:
{{ toYaml .Values.istio.gateway.selector | indent 4 }}
  servers:
    - port:
        number: {{ .Values.istio.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.gateway.hosts }}
        - {{ . | quote }}
        {{- end }}

{{ end }}