apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pathfinder.fullname" . }}
type: Opaque
data:
  {{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}