{{- if .Values.volume.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pathfinder.fullname" . }}-volume
  labels:
    {{- include "pathfinder.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $_ := .Values.volume.secret }}
  {{ $key }}: |
    {{- $.Files.Get (printf "files/%s" $key) | nindent 4 }}
  {{- end }}
{{- end }}