{{- if .Values.env.secret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pathfinder.fullname" . }}-env
  labels:
    {{- include "pathfinder.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}