{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "pathfinder.fullname" . }}
  labels:
    {{- include "pathfinder.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.gateway.hosts }}
  - {{ .host | quote }}
  {{- end }}
  gateways:
    - {{ include "pathfinder.fullname" . }}
  http:
  {{- range .Values.istio.gateway.hosts }}
  {{- range .paths }}
  - match:
      - uri:
          prefix: {{ .path }}
    route:
      - destination:
          host: {{ include "pathfinder.fullname" $ }}
          port:
            number: {{ $.Values.service.port }}
  {{- end }}
  {{- end }}
{{ end}}