authentik:
  secret_key: "f2IEP6FTBYD+uMJdR2q5qx1IwjoXpISOGDQYwau0Q/IzSoeeZuE9/OJ5/vljgHi8PDpbEx+5ZngDdDTy"

  error_reporting:
    enabled: false

  postgresql:
    password: admin

postgresql:
  enabled: true
  auth:
    password: admin

server:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres

  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true

worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres

  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true