authentik:
  secret_key: "f2IEP6FTBYD+uMJdR2q5qx1IwjoXpISOGDQYwau0Q/IzSoeeZuE9/OJ5/vljgHi8PDpbEx+5ZngDdDTy"

  error_reporting:
    enabled: false

  postgresql:
    password: admin

postgresql:
  enabled: true
  auth:
    password: admin
