apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

configMapGenerator:
  - name: keycloak-config
    files:
      - config/master.yaml

generatorOptions:
  disableNameSuffixHash: true