apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apis

configMapGenerator:
  - name: app-config
    files:
      - config.yaml

secretGenerator:
  - name: app-secret
    files:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true