apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-gen
  namespace: default
  labels:
    app: traffic-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-gen
  template:
    metadata:
      labels:
        app: traffic-gen
    spec:
      containers:
        - name: traffic-gen
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                wget -qO- http://httpbin.default.svc.cluster.local:8000/get;
                sleep 1;
              done

