realm: master
enabled: true

identityProviders:
  - alias: adfs
    providerId: oidc
    enabled: true

    config:
      discoveryUrl: https://adfs.company.com/adfs/.well-known/openid-configuration
      clientId: "123456"
      clientSecret: "123456"
      useJwksUrl: "true"
      validateSignature: "true"