apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: configs
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  application: my-app
          - git:
              repoURL: https://github.com/highonsemicolon/pathfinder.git
              revision: main
              directories:
                - path: gitops/applications/my-app/configs/*
  template:
    metadata:
      name: '{{metadata.labels.application}}-configs-{{path[4]}}-{{metadata.labels.environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/highonsemicolon/pathfinder.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: '{{path[4]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true