apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"

spec:
  project: default

  source:
    repoURL: https://github.com/highonsemicolon/pathfinder.git
    targetRevision: main
    path: gitops/infrastructure/keycloak/instance

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true