apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            application: my-app
  template:
    metadata:
      name: '{{metadata.labels.application}}-root-{{metadata.labels.environment}}'
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
    spec:
      project: default
      source:
        repoURL: https://github.com/highonsemicolon/pathfinder.git
        targetRevision: main
        path: gitops/my-app-root
      destination:
        server: '{{server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true