name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/publish-helm.yaml'
      - 'README.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
          mkdir -p .deploy
          helm lint helm
          helm package helm --destination .deploy

      - name: Generate index.yaml
        run: |
          helm repo index .deploy --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Copy README to deploy directory
        run: cp README.md .deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .deploy
          publish_branch: gh-pages
          enable_jekyll: true
